# Generated by Django 2.1.3 on 2018-11-26 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact_box', '0002_auto_20181126_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contact_box.Person'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='email',
            name='type',
            field=models.IntegerField(choices=[(1, 'domowy'), (2, 'prywatny'), (3, 'słżbowy')]),
        ),
    ]
