# Generated by Django 2.1.3 on 2018-11-26 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_box', '0003_auto_20181126_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='type',
            field=models.IntegerField(choices=[(1, 'domowy'), (2, 'prywatny'), (3, 'służbowy')]),
        ),
        migrations.AlterField(
            model_name='phone',
            name='type',
            field=models.SmallIntegerField(choices=[(1, 'domowy'), (2, 'prywatny'), (3, 'służbowy')]),
        ),
    ]
