# Generated by Django 2.1.3 on 2018-11-26 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_box', '0004_auto_20181126_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
